uint8 SUBSCRIBE = 0  # Remote forwards messages to local
uint8 BRIDGE = 1     # Remote and local forward messages to each other

uint8 action
string ip     # IPv4 address
uint16 port
string mtype  # Message type (e.g. std_msgs/String)
string topic
---
bool success
